#ifndef GATE_ITEMS_H
#define GATE_ITEMS_H

typedef enum ItemUnlockKind
{
    ITUNLOCK_ALLUP,
    ITUNLOCK_SPEEDMAX,
    ITUNLOCK_SPEEDMIN,
    ITUNLOCK_OFFENSEMAX,
    ITUNLOCK_DEFENSEMAX,
    ITUNLOCK_CHARGEMAX,
    ITUNLOCK_CHARGENONE,
    ITUNLOCK_CANDY,
    ITUNLOCK_FOODMAXIMTOMATO,
    ITUNLOCK_FOODENERGYDRINK,
    ITUNLOCK_FOODICECREAM,
    ITUNLOCK_FOODRICEBALL,
    ITUNLOCK_FOODCHICKEN,
    ITUNLOCK_FOODCURRY,
    ITUNLOCK_FOODRAMEN,
    ITUNLOCK_FOODOMELET,
    ITUNLOCK_FOODHAMBURGER,
    ITUNLOCK_FOODSUSHI,
    ITUNLOCK_FOODHOTDOG,
    ITUNLOCK_FOODAPPLE,
    ITUNLOCK_FIREWORKS,
    ITUNLOCK_PANICSPIN,
    ITUNLOCK_TIMEBOMB,
    ITUNLOCK_GORDO,
    ITUNLOCK_HYDRA1,
    ITUNLOCK_HYDRA2,
    ITUNLOCK_HYDRA3,
    ITUNLOCK_DRAGOON1,
    ITUNLOCK_DRAGOON2,
    ITUNLOCK_DRAGOON3,
    ITUNLOCK_NUM,
} ItemUnlockKind;

void GateItems_OnBoot();
void GateItems_FilterSpawnTables();
void GateItems_FilterEventDropTables();
int GateItems_UnlockItem(ItemUnlockKind kind);

#endif
