#ifndef AP_SAVE_ICON_H
#define AP_SAVE_ICON_H

#include "os.h"

#define AP_SAVE_ICON_W 32
#define AP_SAVE_ICON_H 32

// 32x32 RGB5A3 (GX 4x4-tiled) memory-card icon, generated by scripts/convert_save_icon.py.
extern const u16 ap_save_icon[AP_SAVE_ICON_W * AP_SAVE_ICON_H];

#endif
